- name: Install & Configure ISC Kea DHCP4
  hosts: all
  remote_user: arran
  become: true
  vars:
    files: files/
    server_name: "{{ inventory_hostname }}"
    network:
      conf: /etc/netplan/netplan.yaml
      interfaces:
        enp0s3:
          type: dhcp4
        enp0s8:
          type: static 
          addresses:
           - { ip: 192.168.100.1, prefix: 24 }
    dhcp:
      conf: /etc/kea/kea-dhcp4.conf
      interface: enp0s8
      subnet:
        address: 192.168.100.0/24
        first: 192.168.100.100
        last: 192.168.100.200
        dns: 192.168.178.1
        routers: 192.168.100.1
        domain:
      leases:
        file: /var/lib/kea/dhcp4.leases
  
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: Remove 00-installer-config.yaml
    file:
      path: /etc/netplan/00-installer-config.yaml
      state: absent

  - name: Generate Netplan config
    template:
      src: "{{ files }}/netplan.yaml.j2"
      dest: "{{ network.conf }}"
      owner: root
      group: root
      mode: '0644'
    notify:
      - Systemctl reload systemd-networkd.service

  - name: Install ISC Kea DHCP4 Server
    apt:
      name: kea-dhcp4-server
      state: present

  - name: Generate Kea DHCP IPv4 config
    template:
      src: "{{ files }}/kea-dhcp4.conf.j2"
      dest: "{{ dhcp.conf }}"
      owner: root
      group: root
      mode: '0644'
    notify:
      - Systemctl reload kea-dhcp4-server.service
    
  handlers:
    - name: Systemctl reload systemd-networkd.service
      systemd:
        name: systemd-networkd.service
        state: reloaded

    - name: Systemctl reload kea-dhcp4-server.service
      systemd:
        name: kea-dhcp4-server.service
        state: restarted
    

    